CREATE MEMORY TABLE STREAM_STATUS(STREAM_ID VARCHAR(255) NOT NULL PRIMARY KEY, STATUS VARCHAR(30) NOT NULL, SIZE BIGINT NOT NULL, CREATED TIMESTAMP, LAST_UPDATED TIMESTAMP);

INSERT INTO STREAM_STATUS(STREAM_ID, STATUS, SIZE, CREATED, LAST_UPDATED) VALUES('BusyFile', 'IN_PROGRESS', 1024, NOW(), NOW());
INSERT INTO STREAM_STATUS(STREAM_ID, STATUS, SIZE, CREATED, LAST_UPDATED) VALUES('DoneFile', 'SUCCESSFUL', 2048, NOW(), NOW());